spring:
  application:
    name: CapstoneDesign
  config:
    import: optional:application-dev.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
