spring:
  application:
    name: CapstoneDesign
  config:
    import: optional:application-dev.yml

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-901.clokoka2yxih.ap-northeast-2.rds.amazonaws.com:3306/capstone
#    username: admin
#    password: 20250519

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/capstone
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
